export const userData = [
  {
    month: 'Jan.',
    sales: 4782,
  },
  {
    month: 'Feb.',
    sales: 3567,
  },
  {
    month: 'Mar.',
    sales: 1256,
  },
  {
    month: 'Apr.',
    sales: 3673,
  },
  {
    month: 'May.',
    sales: 6780,
  },
  {
    month: 'Jun.',
    sales: 3984,
  },
  {
    month: 'Jul.',
    sales: 5699,
  },
  {
    month: 'Aug.',
    sales: 9534,
  },
  {
    month: 'Sep.',
    sales: 2346,
  },
  {
    month: 'Oct.',
    sales: 9756,
  },
  {
    month: 'Nov.',
    sales: 6957,
  },
  {
    month: 'Dec.',
    sales: 2387,
  },
];

export const userListRows = [
  {
    id: 1,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=901',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 2,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=902',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 3,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=903',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 4,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=904',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 5,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=905',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 6,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=906',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 7,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=907',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 8,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=908',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 9,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=909',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 10,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=910',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 11,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=911',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 12,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=912',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 13,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=913',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 14,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=914',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
  {
    id: 15,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=915',
    email: 'Mazta333@gmail.com',
    status: true,
    transaction: '$55.66',
  },
];

export const productColumns = [
  {
    field: 'sku',
    headerName: 'SKU',
    width: 130,
  },
  {
    field: 'price',
    headerName: 'Price',
    width: 100,
  },
  {
    field: 'status',
    headerName: 'Status',
    width: 100,
    renderCell: (params) => {
      return `${params.row.status ? 'Active' : 'Inactive'} `;
    },
  },
  {
    field: 'instock',
    headerName: 'Stock',
  },
  {
    field: 'createdtime',
    headerName: 'Created',
    width: 150,
  },
  {
    field: 'profitmargin',
    headerName: 'Profit',
    width: 100,
  },
];

export const productRows = [
  {
    id: 1,
    sku: 'MOZ14816X',
    status: false,
    price: 327,
    instock: 273,
    createdtime: '2020/11/27',
    profitmargin: '23%',
  },
  {
    id: 2,
    sku: 'MOZ17824X',
    status: true,
    price: 343,
    instock: 273,
    createdtime: '2021/1/17',
    profitmargin: '28%',
  },
  {
    id: 3,
    sku: 'MOZ21526X',
    status: true,
    price: 274,
    instock: 402,
    createdtime: '2020/10/18',
    profitmargin: '46%',
  },
  {
    id: 4,
    sku: 'MOZ23698X',
    status: true,
    price: 273,
    instock: 473,
    createdtime: '2021/4/24',
    profitmargin: '22%',
  },
  {
    id: 5,
    sku: 'MOZ30772X',
    status: true,
    price: 213,
    instock: 395,
    createdtime: '2022/3/28',
    profitmargin: '50%',
  },
  {
    id: 6,
    sku: 'MOZ37656X',
    status: true,
    price: 325,
    instock: 467,
    createdtime: '2020/10/11',
    profitmargin: '40%',
  },
  {
    id: 7,
    sku: 'MOZ38935X',
    status: true,
    price: 293,
    instock: 119,
    createdtime: '2021/2/25',
    profitmargin: '46%',
  },
  {
    id: 8,
    sku: 'MOZ44278X',
    status: true,
    price: 296,
    instock: 298,
    createdtime: '2022/3/17',
    profitmargin: '29%',
  },
  {
    id: 9,
    sku: 'MOZ45748X',
    status: true,
    price: 297,
    instock: 363,
    createdtime: '2021/7/31',
    profitmargin: '36%',
  },
  {
    id: 10,
    sku: 'MOZ57800X',
    status: false,
    price: 271,
    instock: 371,
    createdtime: '2022/2/24',
    profitmargin: '22%',
  },
  {
    id: 11,
    sku: 'MOZ58953X',
    status: true,
    price: 324,
    instock: 355,
    createdtime: '2021/11/3',
    profitmargin: '48%',
  },
  {
    id: 12,
    sku: 'MOZ65031X',
    status: true,
    price: 316,
    instock: 455,
    createdtime: '2020/10/21',
    profitmargin: '33%',
  },
  {
    id: 13,
    sku: 'MOZ66921X',
    status: true,
    price: 232,
    instock: 251,
    createdtime: '2021/1/22',
    profitmargin: '50%',
  },
  {
    id: 14,
    sku: 'MOZ70560X',
    status: true,
    price: 341,
    instock: 294,
    createdtime: '2020/11/19',
    profitmargin: '32%',
  },
  {
    id: 15,
    sku: 'MOZ74936X',
    status: true,
    price: 222,
    instock: 360,
    createdtime: '2021/11/2',
    profitmargin: '50%',
  },
  {
    id: 16,
    sku: 'MOZ95000X',
    status: false,
    price: 260,
    instock: 416,
    createdtime: '2021/6/19',
    profitmargin: '37%',
  },
  {
    id: 17,
    sku: 'MOZ95021X',
    status: false,
    price: 323,
    instock: 494,
    createdtime: '2022/2/21',
    profitmargin: '34%',
  },
  {
    id: 18,
    sku: 'MOZ95355X',
    status: false,
    price: 232,
    instock: 157,
    createdtime: '2021/10/30',
    profitmargin: '21%',
  },
  {
    id: 19,
    sku: 'MOZ95444X',
    status: true,
    price: 341,
    instock: 175,
    createdtime: '2021/6/30',
    profitmargin: '23%',
  },
  {
    id: 20,
    sku: 'MOZ96630X',
    status: false,
    price: 214,
    instock: 163,
    createdtime: '2021/3/13',
    profitmargin: '36%',
  },
];

export const informationColumnsList = [
  {
    type: 'Product Name',
    name: 'productName',
    placeholder: 'Amazing Product',
  },
  { type: 'SKU', name: 'sku', placeholder: 'MOZ17824X' },
  { type: 'Condition', name: 'condition', placeholder: 'New' },
  { type: 'Status', name: 'status', placeholder: 'Active' },
  { type: 'Carrier', name: 'carrier', placeholder: 'FedEx' },
];

export const priceColumnsList = [
  { type: 'Sales Price', name: 'price', placeholder: '$156.00' },
  { type: 'Discount', name: 'discount', placeholder: '20%' },
  { type: 'Sales Price (2B)', name: 'price2b', placeholder: '$136.00' },
  { type: 'Discount (2B)', name: 'discount2b', placeholder: '30%' },
  { type: 'Sales Price (VIP)', name: 'priceVip', placeholder: '$126.00' },
  { type: 'Discount (VIP)', name: 'discountVip', placeholder: '35%' },
];

export const otherColumnsList = [
  { type: 'Other1', name: 'other1', placeholder: 'Other1' },
  { type: 'Other2', name: 'other2', placeholder: 'Other2' },
  { type: 'Other3', name: 'other3', placeholder: 'Other3' },
  { type: 'Other4', name: 'other4', placeholder: 'Other4' },
  { type: 'Other5', name: 'other5', placeholder: 'Other5' },
  { type: 'Other6', name: 'other6', placeholder: 'Other6' },
  { type: 'Other7', name: 'other7', placeholder: 'Other7' },
];
