export const userData = [
  {
    month: 'Jan.',
    sales: 4782,
  },
  {
    month: 'Feb.',
    sales: 3567,
  },
  {
    month: 'Mar.',
    sales: 1256,
  },
  {
    month: 'Apr.',
    sales: 3673,
  },
  {
    month: 'May.',
    sales: 6780,
  },
  {
    month: 'Jun.',
    sales: 3984,
  },
  {
    month: 'Jul.',
    sales: 5699,
  },
  {
    month: 'Aug.',
    sales: 9534,
  },
  {
    month: 'Sep.',
    sales: 2346,
  },
  {
    month: 'Oct.',
    sales: 9756,
  },
  {
    month: 'Nov.',
    sales: 6957,
  },
  {
    month: 'Dec.',
    sales: 2387,
  },
];

export const userListRows = [
  {
    id: 1,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=901',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 2,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=902',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 3,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=903',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 4,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=904',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 5,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=905',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 6,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=906',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 7,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=907',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 8,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=908',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 9,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=909',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 10,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=910',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 11,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=911',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 12,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=912',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 13,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=913',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 14,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=914',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
  {
    id: 15,
    userName: 'Mozta',
    avatar: 'https://picsum.photos/300/300?random=915',
    email: 'Mazta333@gmail.com',
    status: 'active',
    transaction: '$55.66',
  },
];
